proxy:
  image: takumon/proxy:1.0
  links:
    - identidock
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=192.168.1.5
    - NGINX_PROXY=http://identidock:9090
identidock:
  build: .
  environment:
    ENV: PROD
  volumes:
    - ./app:/app
  links:
    - dnmonster
    - redis

dnmonster:
  image: amouat/dnmonster:1.0

redis:
  image: redis:3.0

logspout:
  image: amouat/logspout-logstash:1.0
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "8000:80"
